- id: https://doi.org/10.1145/3494991
  image: images/face.png
  extra-links:
    - type: manubot
      link: https://dl.acm.org/doi/abs/10.1145/3494991
  tags:
    - Wearables, Machine Learning
    
- id: https://doi.org/10.1145/3410530.3414397
  image: images/vibroscale.png
  extra-links:
    - type: manubot
      link: https://dl.acm.org/doi/abs/10.1145/3410530.3414397
  tags:
    - Mobile Computing, Machine Learning
    
- id: https://doi.org/10.1145/3397313
  image: images/necksense.png
  extra-links:
    - type: manubot
      link: https://dl.acm.org/doi/abs/10.1145/3397313?casa_token=9tooeuDt1mkAAAAA:ERCLKS0R_-0fRPLchzWHgyJzhiWlf6SMglMrCjGnqjZm0fAY4g4wMJql9L5D752QAhQ0cXw-PMFNEw
  tags:
    - Mobile Computing, Machine Learning, Wearables
    
- id: https://doi.org/10.1145/3411824
  image: images/synch.png
  extra-links:
    - type: manubot
      link: https://dl.acm.org/doi/abs/10.1145/3411824
  tags:
    - Mobile Computing, Machine Learning
    
    
- id: https://doi.org/10.1145/3460421.3478811
  image: images/heat.png
  extra-links:
    - type: manubot
      link: https://dl.acm.org/doi/abs/10.1145/3460421.3478811
  tags:
    - Wearables, Machine Learning
